### ISSUE TITLE
setuidgid: usage: setuidgid account child

### ISSUE THREAD

**Issue by pirateandy** [dokku-alt/dokku-alt#163] opened 2015-01-15 02:42 UTC
Almost every time I try to deploy a static web build with https://github.com/florianheinemann/buildpack-nginx.git

setuidgid: usage: setuidgid account child

I get this error when i do dokku logs app. I even try to delete the app and re-deploy it but the same message appears. The only way I've found to fix this problem is to destroy the EC2 instance and launch a new set up process. I've had to do this about 15 times now. 

Any help would be greatly appreciated.

**Comment by mlitwiniuk** [comment] 2015-01-15 12:16
I don't know, if this is best place for this bug report, but I can confirm it.
It also happened with default ruby/rails buildpack, but after changing worker to unicorn with Procfile, it started working.

**Comment by rranshous** [comment] 2015-01-19 01:05
confirmed seeing this with:
 - dokku-alt: https://github.com/dokku-alt/dokku-alt/commit/c07312e6d096900019d6ba18bcf49af6cb2af68d
 - rails 4 application: https://github.com/rranshous/willrobotsreplaceme/commit/618c9ef42025dbca329d1c40b47b791892b15b4a

fixed with this commit: https://github.com/rranshous/willrobotsreplaceme/commit/ac6cfe55f4ea08f6e6c643628b949911940dc608

**Comment by mc0e** [comment] 2015-03-03 22:43
I'm getting the same `setuidgid` error when trying to use a different buildpack.  I have a `.env` file with `export BUILDPACK_URL=https://github.com/essh/heroku-buildpack-nginx.git` in it.  No rails involved, so I'm dubious of rranshous reported fix.

The buildpack gets run as user ID=1000, both when  building the app, and when running it.  anything about setting uid or gid is probably going to fail.

**Comment by cpursley** [comment] 2015-03-04 01:19
Experiencing the same issue here. Rails app won't boot up.

**Comment by marothstein** [comment] 2015-03-04 04:08
Any resolution here?

**Comment by ayufan** [comment] 2015-03-04 10:42
Can you download buildstep image?

Check which one you use:
```docker images | grep ayufan/dokku-alt-buildstep```

And then do (most likely):
```docker pull ayufan/dokku-alt-buildstep:cedar-14```

And rebuild app:
```dokku rebuild myapp```

It should work.

**Comment by mc0e** [comment] 2015-03-04 12:31
With the buildpack as in my previous comment, I ran a shell in the container (which had failed to start) and poked around.  The setuidgid line appears at the end of the `/start` script:

    exec setuidgid u1000 $(eval echo ${command})

Which comes from buidstep, <a href="https://github.com/progrium/buildstep/blob/2f56cec234b6fd952528200f350132727cf5a431/builder/builder">here</a>, so it's going to be the case for any buildpack.

This can't work, because we are already running as uid `u1000`.

I already had <a href="https://github.com/dokku-alt/dokku-alt/issues/206">concerns</a> that because the container was being run as `u1000`, including both the build and execution, there could not be adequate permissions protection of web app code which should not be writeable by the web process user.  In issue #206, It was suggested that I do:

     dokku_mc config:set <APP_NAME> DOKKU_USER_ID=0

This doesn't seem to work.

**Comment by ayufan** [comment] 2015-03-04 12:38
Ok. I'll check that buildpack and see why it breaks. Do you have Procfile or not?

**Comment by mc0e** [comment] 2015-03-04 13:09
No Procfile

**Comment by paralin** [comment] 2015-03-08 23:45
Same thing happening to me... Can't launch anything. Please help! :)

**Comment by 97-109-107** [comment] 2015-03-11 15:33
Confirmed here too.
Upon setting:
``
 dokku_mc config:set <APP_NAME> DOKKU_USER_ID=0
`` 

as @mc0e had been suggested I get:

``
time="2015-03-11T15:32:30Z" level="fatal" msg="Error response from daemon: No such container: e7d005ea1916a532160eb9ae5634f0237ab6e451eb3cf9965622b051230f312f" 
`` 
when trying to see the app's log

**Comment by enriqueromero** [comment] 2015-03-12 15:27
Same issue here! Tried all of the above and no dice!

**Comment by ayufan** [comment] 2015-03-12 15:53
Yay! It's fixed!

Please pull buildstep image:
```docker pull ayufan/dokku-alt-buildstep:cedar-14```

And let me know if it works for you now ;)

**Closed by ayufan** 2015-03-12 15:53 UTC

**Comment by enriqueromero** [comment] 2015-03-12 16:21
Pulled and tried it. Still getting "setuidgid: usage: setuidgid account child" :(

**Comment by ayufan** [comment] 2015-03-12 16:22
If not please as root do: ```dokku plugins-install``` and rebuild then.

**Comment by enriqueromero** [comment] 2015-03-12 16:25
root@node-login:~# dokku plugins-install
gpg: requesting key 773CEBs0 from hkp server keyserver.ubuntu.com
gpg: key 773CEBs0: "Richard Kreuter <richard@10gen.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
root@node-login:~# dokku rebuild node-login
root@node-login:~# dokku logs node-login
setuidgid: usage: setuidgid account child

**Comment by ayufan** [comment] 2015-03-12 16:26
No way. Please join: https://gitter.im/dokku-alt/dokku-alt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by enriqueromero** [comment] 2015-03-12 23:45
Ok it worked after I pulled dokku-alt version. Now I have another issue not related(I hope). Posted it on the chat. tks.

**Comment by 97-109-107** [comment] 2015-03-13 09:32
@ayufan Thanks for the help!

To anybody else, here's the steps that fixed it for me.

Inside the repo
-  ``.env`` contains ``export BUILDPACK_URL=https://github.com/florianheinemann/buildpack-nginx.git``
- presence of ``.static``

On the box where dokku is:
- ``sudo docker pull ayufan/dokku-alt-buildstep:cedar-14``

Finally I only needed to push the repo to the dokku remote and it works.

**Comment by ayufan** [comment] 2015-03-13 09:32
Great to hear :)

On Friday, March 13, 2015, 97-109-107 <notifications@github.com> wrote:

> @ayufan <https://github.com/ayufan> Thanks for the help!
>
> To anybody else, here's the steps that fixed it for me.
>
> Inside the repo
>
>    - .env contains export BUILDPACK_URL=
>    https://github.com/florianheinemann/buildpack-nginx.git
>    - presence of .static
>
> On the box where dokku is:
>
>    - sudo docker pull ayufan/dokku-alt-buildstep:cedar-14
>
> Finally I only needed to push the repo to the dokku remote and it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dokku-alt/dokku-alt/issues/163#issuecomment-78887177>.
>


-- 
Kamil Trzciński

ayufan@ayufan.eu
www.ayufan.eu

**Comment by enriqueromero** [comment] 2015-03-13 16:25
You guys have been great help. As I mentioned before I'm new to this. This may be unrelated but this is where I'm now at:  

1.) I enter the url xxx.xxx.xxx:49155 assigned to my site and get the, "It looks like you are trying to access MongoDB over HTTP on the native driver port" message.     

2.) I enter the url xxx:xxx:xxx:80 and I get the "502 bad gateway nginx" message.  

I'm still not there and not quite sure what's next. 

                                      Thanks
